require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.lualine"
require "user.comment"
require "user.indentline"
require "skyturtle.gitsigns"
require "skyturtle.lsp"
require "user.cmp"
require "user.treesitter"
require "user.nvim-tree"
require "user.telescope"
require "user.colorscheme"
require "user.autopairs"
require "user.toggleterm"
require "user.impatient"
require "user.illuminate"
-- require "user.dap"
-- require "user.autocommands"
